name: "Action-contribution-recorder"
description: "This GitHub Action automatically generates a leader board based on contributors' activity and displays it in your README, recognizing and attracting contributors to your project."
inputs:
    GH_TOKEN:
        description: "GITHUB_TOKEN"
        required: true
    GH_REPOSITORY:
        description: "GITHUB_REPOSITORY"
        required: false
        default: ${{ github.repository }}
    BRANCH:
        description: "Branch name"
        required: true
    COMMITTER_USERNAME:
        description: "committer username"
        default: "contribution-recorder-bot"
        required: false
    COMMITTER_EMAIL:
        description: "committer email"
        default: ""
        required: false
    COMMIT_MESSAGE:
        description: "commit message"
        default: "feat:🎸 update contributor leader board"
        required: false
    RANK_JSON_PATH:
        description: "json file path"
        required: false
        default: "./.github/contributor-leader-board.json"
    MARKDOWN_PATH:
        description: "markdown file path"
        required: false
        default: "./README.md"
    DISPLAY_CONTRIBUTOR_COUNTS:
        description: "display contributor counts"
        required: false
        default: "10"
    MARKDOWN_INSERT_KEY:
        description: "markdown insert key"
        required: false
        default: "CONTRIBUTION-LEADER-BOARD-TABLE"
    IS_SKIP_COMMITTING:
        description: "skip committing"
        required: false
        default: "false"
    IS_SKIPPING_WRITING_FILES:
        description: "skip writing files"
        required: false
        default: "false"

runs:
    using: node16
    main: dist/index.js

