name: "Action-contribution-recorder"
description: "This GitHub Action automatically generates a leader board based on contributors' activity and displays it in your README, recognizing and attracting contributors to your project."
inputs:
    GITHUB_TOKEN:
        description: "GITHUB_TOKEN"
        required: true
    GITHUB_REPOSITORY:
        description: "GITHUB_REPOSITORY"
        required: true
    RANK_JSON_PATH:
        description: "json file path"
        required: false
        default: "./contributor-leader-board.json"
    MARKDOWN_PATH:
        description: "markdown file path"
        required: false
        default: "./README.md"
    DISPLAY_CONTRIBUTOR_COUNTS:
        description: "display contributor counts"
        required: false
        default: "10"
    MARKDOWN_INSERT_KEY:
        description: "markdown insert key"
        required: false
        default: "CONTRIBUTION-LEADER-BOARD-TABLE"
    branch:
        description: "Branch name"
        required: true

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v3
          with:
              fetch-depth: 0
              ref: ${{ inputs.branch }}

        - uses: actions/setup-node@v2
          with:
              node-version: 16

        - name: Run main javascript
          env:
              RECORD_DAY_RANGE: "300" #TODO remove
              GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
              GITHUB_REPOSITORY: ${{ inputs.GITHUB_REPOSITORY }}
              RANK_JSON_PATH: ${{ inputs.RANK_JSON_PATH }}
              MARKDOWN_PATH: ${{ inputs.MARKDOWN_PATH }}
              DISPLAY_CONTRIBUTOR_COUNTS: ${{ inputs.DISPLAY_CONTRIBUTOR_COUNTS }}
              MARKDOWN_INSERT_KEY: ${{ inputs.MARKDOWN_INSERT_KEY }}
          working-directory: ./
          shell: bash
          run: node dist/index.js

        - name: check for changes
          shell: bash
          run: |
              if git diff --exit-code; then
                echo "changes_exist=false" >> "$GITHUB_ENV"
              else
                echo "changes_exist=true" >> "$GITHUB_ENV"
              fi

        - name: Commit
          shell: bash
          if: ${{ env.changes_exist == 'true' }}
          run: |
              git config --global user.name 'contribution-recorder-bot'
              git commit -am "feat:🎸 update contributor leader board"

        - name: Push changes
          uses: ad-m/github-push-action@master
          if: ${{ env.changes_exist == 'true' }}
          with:
              github_token: ${{ inputs.GITHUB_TOKEN }}
              branch: ${{ inputs.branch }}

