name: "main"
on:
    pull_request:
        types:
            - closed
        branches:
            - main
jobs:
    auto-tag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: ./.github/workflows/auto-tag.yml

